Repository firefox-devtools/debugger, pull requests merged in 2018-04, with the labels that each got.

#5784 [QuickOpen] Filter file search if a project directory root is set
  src/actions/tests/ui.spec.js
  src/components/QuickOpenModal.js
  src/reducers/ast.js
  src/selectors/getRelativeSources.js
  src/selectors/index.js
  src/selectors/visibleBreakpoints.js
  src/utils/quick-open.js
Labels: pr-needs-review

#5772 Add flow coverage to parser/types.js
  src/actions/preview.js
  src/actions/types.js
  src/components/Editor/index.js
  src/components/PrimaryPanes/Outline.js
  src/reducers/ast.js
  src/utils/ast.js
  src/utils/editor/get-expression.js
  src/utils/editor/source-documents.js
  src/utils/quick-open.js
  src/utils/tests/__snapshots__/ast.spec.js.snap
  src/workers/parser/getSymbols.js
  src/workers/parser/index.js
  src/workers/parser/tests/__snapshots__/getSymbols.spec.js.snap
  src/workers/parser/types.js
  src/workers/parser/utils/formatSymbols.js
  src/workers/parser/utils/inferClassName.js
  src/workers/parser/utils/simple-path.js
Labels: pr-needs-review

#5823 Get breakpoint text
  src/actions/breakpoints/addBreakpoint.js
  src/actions/breakpoints/syncBreakpoint.js
  src/actions/breakpoints/tests/__snapshots__/syncing.spec.js.snap
  src/actions/tests/__snapshots__/breakpoints.spec.js.snap
  src/components/SecondaryPanes/Breakpoints.css
  src/components/SecondaryPanes/Breakpoints.js
  src/utils/breakpoint/index.js
  src/utils/source.js
Labels: pr-needs-review

#5830 Document preview
  src/test/mochitest/browser.ini
  src/test/mochitest/browser_dbg-preview-module.js
  src/test/mochitest/browser_dbg-preview.js
  src/test/mochitest/examples/doc-preview.html
  src/test/mochitest/examples/preview.js
  src/test/mochitest/head.js
Labels: pr-wip

#5845 New Breakpoints UI: Group Breakpoints
  src/components/SecondaryPanes/Breakpoints.css
  src/components/SecondaryPanes/Breakpoints.js
  src/test/mochitest/browser_dbg-breakpoints-toggle.js
  src/test/mochitest/browser_dbg-breakpoints.js
  src/test/mochitest/browser_dbg-browser-content-toolbox.js
  src/test/mochitest/head.js
Labels: pr-needs-review

#5693 [Preview] Evaluate Object properties with an assignment
  src/workers/parser/getSymbols.js
  src/workers/parser/tests/__snapshots__/getSymbols.spec.js.snap
  src/workers/parser/tests/fixtures/callExpressions.js
  src/workers/parser/tests/fixtures/object-expressions.js
  src/workers/parser/tests/getSymbols.spec.js
  src/workers/parser/utils/helpers.js
Labels: pr-wip

#5851 Switched getExtraProps to use findClosestFunction to get the component name.
  src/actions/ast.js
  src/actions/pause/fetchExtra.js
  src/actions/pause/fetchScopes.js
  src/actions/pause/index.js
  src/actions/pause/mapFrames.js
  src/actions/pause/setExtra.js
  src/actions/preview.js
  src/actions/types.js
  src/components/Editor/EditorMenu.js
  src/reducers/pause.js
  src/utils/ast.js
  src/utils/breakpoint/astBreakpointLocation.js
  src/utils/function.js
  src/workers/parser/index.js
Labels: pr-needs-review

#5864 Syntax-highlight breakpoints
  src/components/SecondaryPanes/BreakpointItem.js
  src/components/SecondaryPanes/Breakpoints.css
  src/components/SecondaryPanes/Breakpoints.js
  src/utils/breakpoint/create-editor.js
  src/utils/breakpoint/index.js
  webpack.config.js
Labels: pr-needs-review

#5868 [QuickOpen] Path is too wide #5860
  src/components/shared/ResultList.css
Labels: pr-needs-review

#5716 [Sources] Auto expand path of selected source
  src/components/PrimaryPanes/SourcesTree.js
  src/components/shared/ManagedTree.js
  src/components/tests/__snapshots__/SourcesTree.spec.js.snap
  src/test/mochitest/browser_dbg-asm.js
  src/test/mochitest/browser_dbg-sources.js
Labels: pr-needs-review

#5878 [Preview] stop showing preview for the wrong original files
  src/actions/preview.js
  src/components/Editor/Preview/index.js
  src/selectors/isSelectedFrameVisible.js
  src/test/mochitest/browser_dbg-preview-source-maps.js
  src/test/mochitest/browser_dbg-preview.js
Labels: pr-needs-review

#5885 [Sources] Reveal in tree opens the left sidebar
  src/actions/ui.js
Labels: pr-needs-review

#5861 Fix webpack roots
  src/actions/tests/ui.spec.js
  src/components/PrimaryPanes/SourcesTree.js
  src/selectors/getRelativeSources.js
  src/test/mochitest/browser_dbg-sources.js
  src/utils/sources-tree/addToTree.js
  src/utils/sources-tree/getDirectories.js
  src/utils/sources-tree/getURL.js
  src/utils/sources-tree/tests/__snapshots__/addToTree.spec.js.snap
  src/utils/sources-tree/tests/__snapshots__/collapseTree.spec.js.snap
  src/utils/sources-tree/tests/__snapshots__/sortTree.spec.js.snap
  src/utils/sources-tree/tests/__snapshots__/updateTree.spec.js.snap
  src/utils/sources-tree/tests/collapseTree.spec.js
  src/utils/sources-tree/tests/utils.spec.js
Labels: pr-needs-review

#5882 [ProjectSearch] Focus state colors are a bit off #5863
  src/components/ProjectSearch.css
Labels: pr-needs-review

#5644 Improve evaluating expressions when pausing
  src/actions/expressions.js
  src/actions/pause/fetchExtra.js
  src/actions/pause/paused.js
  src/actions/pause/resumed.js
  src/actions/preview.js
  src/actions/sources/tests/select.spec.js
  src/actions/tests/ast.spec.js
  src/actions/tests/expressions.spec.js
  src/actions/tests/helpers/threadClient.js
  src/actions/tests/pause.spec.js
  src/actions/tests/preview.spec.js
  src/actions/types.js
  src/client/firefox/commands.js
  src/client/firefox/types.js
  src/reducers/expressions.js
  src/reducers/pause.js
  src/test/mochitest/browser.ini
  src/test/mochitest/browser_dbg-expressions-error.js
  src/test/mochitest/browser_dbg-expressions.js
  src/test/mochitest/browser_dbg-navigation.js
  src/test/mochitest/browser_dbg-sourcemaps-reload.js
  src/test/mochitest/examples/doc-scripts-debugger.html
  src/test/mochitest/head.js
  src/utils/expressions.js
Labels: pr-needs-review

#5866 Escape no longer closes the modal
  src/components/App.js
Labels: pr-wip

#5853 Previewing destructured variables
  src/workers/parser/getSymbols.js
  src/workers/parser/tests/__snapshots__/getSymbols.spec.js.snap
Labels: pr-wip

#5854 Started highlighting the searched terms when clicking on a ProjectSearch result
  src/actions/file-search.js
  src/actions/navigation.js
  src/components/Editor/index.js
  src/components/ProjectSearch.js
  src/components/tests/ProjectSearch.spec.js
  src/components/tests/__snapshots__/ProjectSearch.spec.js.snap
  src/utils/editor/index.js
  src/utils/editor/source-search.js
Labels: pr-wip

#5871 Handle global-rewrite (Ember-related) original scope resolution
  .prettierignore
  .travis.yml
  src/actions/pause/mapScopes.js
  src/test/mochitest/browser.ini
  src/test/mochitest/browser_dbg-babel-breakpoint-console.js
  src/test/mochitest/browser_dbg-babel-preview.js
  src/test/mochitest/browser_dbg-babel-scopes.js
  src/test/mochitest/browser_dbg-babel-stepping.js
  src/test/mochitest/browser_dbg-ember-quickstart.js
  src/test/mochitest/examples/ember/quickstart/.editorconfig
  src/test/mochitest/examples/ember/quickstart/.ember-cli
  src/test/mochitest/examples/ember/quickstart/.eslintrc.js
  src/test/mochitest/examples/ember/quickstart/.gitignore
  src/test/mochitest/examples/ember/quickstart/.travis.yml
  src/test/mochitest/examples/ember/quickstart/.watchmanconfig
  src/test/mochitest/examples/ember/quickstart/README.md
  src/test/mochitest/examples/ember/quickstart/app/app.js
  src/test/mochitest/examples/ember/quickstart/app/components/.gitkeep
  src/test/mochitest/examples/ember/quickstart/app/controllers/.gitkeep
  src/test/mochitest/examples/ember/quickstart/app/helpers/.gitkeep
  src/test/mochitest/examples/ember/quickstart/app/index.html
  src/test/mochitest/examples/ember/quickstart/app/models/.gitkeep
  src/test/mochitest/examples/ember/quickstart/app/resolver.js
  src/test/mochitest/examples/ember/quickstart/app/router.js
  src/test/mochitest/examples/ember/quickstart/app/routes/.gitkeep
  src/test/mochitest/examples/ember/quickstart/app/styles/app.css
  src/test/mochitest/examples/ember/quickstart/app/templates/application.hbs
  src/test/mochitest/examples/ember/quickstart/app/templates/components/.gitkeep
  src/test/mochitest/examples/ember/quickstart/config/environment.js
  src/test/mochitest/examples/ember/quickstart/config/targets.js
  src/test/mochitest/examples/ember/quickstart/dist/assets/quickstart.css
  src/test/mochitest/examples/ember/quickstart/dist/assets/quickstart.js
  src/test/mochitest/examples/ember/quickstart/dist/assets/quickstart.map
  src/test/mochitest/examples/ember/quickstart/dist/assets/test-support.css
  src/test/mochitest/examples/ember/quickstart/dist/assets/test-support.js
  src/test/mochitest/examples/ember/quickstart/dist/assets/test-support.map
  src/test/mochitest/examples/ember/quickstart/dist/assets/tests.js
  src/test/mochitest/examples/ember/quickstart/dist/assets/tests.map
  src/test/mochitest/examples/ember/quickstart/dist/assets/vendor.css
  src/test/mochitest/examples/ember/quickstart/dist/assets/vendor.js
  src/test/mochitest/examples/ember/quickstart/dist/assets/vendor.map
  src/test/mochitest/examples/ember/quickstart/dist/ember-welcome-page/images/construction.png
  src/test/mochitest/examples/ember/quickstart/dist/index.html
  src/test/mochitest/examples/ember/quickstart/dist/robots.txt
  src/test/mochitest/examples/ember/quickstart/dist/testem.js
  src/test/mochitest/examples/ember/quickstart/dist/tests/index.html
  src/test/mochitest/examples/ember/quickstart/ember-cli-build.js
  src/test/mochitest/examples/ember/quickstart/package-lock.json
  src/test/mochitest/examples/ember/quickstart/package.json
  src/test/mochitest/examples/ember/quickstart/public/robots.txt
  src/test/mochitest/examples/ember/quickstart/testem.js
  src/test/mochitest/examples/ember/quickstart/tests/helpers/.gitkeep
  src/test/mochitest/examples/ember/quickstart/tests/index.html
  src/test/mochitest/examples/ember/quickstart/tests/integration/.gitkeep
  src/test/mochitest/examples/ember/quickstart/tests/test-helper.js
  src/test/mochitest/examples/ember/quickstart/tests/unit/.gitkeep
  src/test/mochitest/examples/ember/quickstart/vendor/.gitkeep
  src/test/mochitest/head.js
  src/utils/pause/mapScopes/findGeneratedBindingFromPosition.js
Labels: pr-needs-review

#5934 Move debugBtn to a better spot
  src/components/SecondaryPanes/CommandBar.js
  src/components/SecondaryPanes/UtilsBar.js
  src/components/shared/Button/CommandBarButton.js
Labels: pr-needs-review

#5960 Cleanup the ember test
  src/test/mochitest/examples/ember/quickstart/README.md
  src/test/mochitest/examples/ember/quickstart/app/app.js
  src/test/mochitest/examples/ember/quickstart/app/components/.gitkeep
  src/test/mochitest/examples/ember/quickstart/app/controllers/.gitkeep
  src/test/mochitest/examples/ember/quickstart/app/helpers/.gitkeep
  src/test/mochitest/examples/ember/quickstart/app/index.html
  src/test/mochitest/examples/ember/quickstart/app/models/.gitkeep
  src/test/mochitest/examples/ember/quickstart/app/resolver.js
  src/test/mochitest/examples/ember/quickstart/app/router.js
  src/test/mochitest/examples/ember/quickstart/app/routes/.gitkeep
  src/test/mochitest/examples/ember/quickstart/app/styles/app.css
  src/test/mochitest/examples/ember/quickstart/app/templates/application.hbs
  src/test/mochitest/examples/ember/quickstart/app/templates/components/.gitkeep
  src/test/mochitest/examples/ember/quickstart/config/environment.js
  src/test/mochitest/examples/ember/quickstart/config/targets.js
  src/test/mochitest/examples/ember/quickstart/dist/ember-welcome-page/images/construction.png
  src/test/mochitest/examples/ember/quickstart/dist/tests/index.html
  src/test/mochitest/examples/ember/quickstart/ember-cli-build.js
  src/test/mochitest/examples/ember/quickstart/package-lock.json
  src/test/mochitest/examples/ember/quickstart/package.json
  src/test/mochitest/examples/ember/quickstart/public/robots.txt
  src/test/mochitest/examples/ember/quickstart/testem.js
  src/test/mochitest/examples/ember/quickstart/tests/helpers/.gitkeep
  src/test/mochitest/examples/ember/quickstart/tests/index.html
  src/test/mochitest/examples/ember/quickstart/tests/integration/.gitkeep
  src/test/mochitest/examples/ember/quickstart/tests/test-helper.js
  src/test/mochitest/examples/ember/quickstart/tests/unit/.gitkeep
  src/test/mochitest/examples/ember/quickstart/vendor/.gitkeep
Labels: pr-needs-review

#5956 Consolidate extra fields
  src/actions/ast.js
  src/actions/pause/extra.js
  src/actions/pause/fetchExtra.js
  src/actions/pause/fetchScopes.js
  src/actions/pause/index.js
  src/actions/pause/setExtra.js
  src/actions/preview.js
Labels: pr-needs-review

#5950 Remove Chrome Scopes
  configs/ci.json
  configs/local.sample.json
  src/components/SecondaryPanes/ChromeScopes.js
  src/components/SecondaryPanes/index.js
  src/utils/prefs.js
Labels: pr-needs-review

#5836 (WIP) Update pause points
  .travis.yml
  src/actions/types/ASTAction.js
  src/client/firefox/commands.js
  src/reducers/ast.js
  src/utils/ast.js
  src/utils/pause/pausePoints.js
  src/workers/parser/getScopes/visitor.js
  src/workers/parser/index.js
  src/workers/parser/pausePoints.js
  src/workers/parser/tests/__snapshots__/pausePoints.spec.js.snap
  src/workers/parser/tests/fixtures/calls.js
  src/workers/parser/types.js
Labels: pr-wip

#5932 Add checkboxes for caught exceptions
  assets/panel/debugger.properties
  assets/panel/prefs.js
  src/components/SecondaryPanes/Breakpoints.css
  src/components/SecondaryPanes/Breakpoints.js
  src/components/SecondaryPanes/BreakpointsDropdown.css
  src/components/SecondaryPanes/BreakpointsDropdown.js
  src/components/SecondaryPanes/CommandBar.css
  src/components/SecondaryPanes/CommandBar.js
  src/components/SecondaryPanes/index.js
  src/reducers/types.js
  src/utils/prefs.js
Labels: pr-needs-review

#5942 Use mc help svg
  assets/images/Svg.js
  assets/images/help.svg
  postcss.config.js
  src/components/SecondaryPanes/CommandBar.css
Labels: pr-needs-review

#5954 Use pausePoints to determine valid pause locations
  src/actions/pause/paused.js
  src/actions/tests/preview.spec.js
  src/reducers/ast.js
  src/reducers/pause.js
  src/types.js
  src/utils/pause/stepping.js
  src/workers/parser/index.js
  src/workers/parser/pauseLocation.js
  src/workers/parser/pausePoints.js
  src/workers/parser/tests/__snapshots__/getSymbols.spec.js.snap
  src/workers/parser/tests/__snapshots__/pausePoints.spec.js.snap
  src/workers/parser/tests/fixtures/control-flow.js
  src/workers/parser/tests/fixtures/func.js
  src/workers/parser/tests/fixtures/pause/blocks.js
  src/workers/parser/tests/fixtures/pause/functions.js
  src/workers/parser/tests/pauseLocation.spec.js
  src/workers/parser/types.js
  src/workers/parser/worker.js
  yarn.lock
Labels: pr-needs-review

#6029 Add the workers to dbg
  docs/dbg.md
  src/client/index.js
  src/test/tests-setup.js
  src/utils/bootstrap.js
  src/workers/parser/index.js
  src/workers/pretty-print/index.js
  src/workers/search/index.js
Labels: pr-needs-review

#6030 Revert "Added VisibilityHandler to handle the mounting and unmounting…
  src/components/App.js
  src/components/shared/VisibilityHandler.js
Labels: pr-needs-review

#6025 Fixes outline issue from our earlier fix to the button
  src/components/shared/Button/Close.css
Labels: pr-needs-review

#5998 Provide a "Skip Pausing" button for the Command Bar
  assets/images/disable-pausing.svg
  assets/panel/debugger.properties
  assets/panel/prefs.js
  src/actions/pause/index.js
  src/actions/pause/skipPausing.js
  src/actions/pause/tests/skipPausing.spec.js
  src/actions/types/PauseAction.js
  src/client/firefox/commands.js
  src/client/firefox/types.js
  src/components/SecondaryPanes/CommandBar.css
  src/components/SecondaryPanes/CommandBar.js
  src/components/SecondaryPanes/index.js
  src/reducers/pause.js
  src/test/mochitest/browser.ini
  src/test/mochitest/browser_dbg-breakpoints-toggle.js
  src/utils/prefs.js
  src/workers/parser/pausePoints.js
Labels: pr-wip

#6041 Defer updating hidden tabs
  src/components/Editor/Tabs.js
Labels: pr-needs-review

#6017 Fix sourcemaps off
  src/actions/sources/newSources.js
  src/actions/sources/tests/newSources.spec.js
  src/utils/test-head.js
Labels: pr-needs-review

#5824 (WIP) Migrate source maps
  .eslintignore
  .eslintrc
  bin/copy-assets.js
  circle.yml
  flow-typed/debugger-html.js
  package.json
  packages/devtools-source-map/LICENSE
  packages/devtools-source-map/README.md
  packages/devtools-source-map/package.json
  packages/devtools-source-map/src/index.js
  packages/devtools-source-map/src/source-map.js
  packages/devtools-source-map/src/tests/fixtures/absolute.js
  packages/devtools-source-map/src/tests/fixtures/absolute.js.map
  packages/devtools-source-map/src/tests/fixtures/bundle.js
  packages/devtools-source-map/src/tests/fixtures/bundle.js.map
  packages/devtools-source-map/src/tests/fixtures/empty.js
  packages/devtools-source-map/src/tests/fixtures/empty.js.map
  packages/devtools-source-map/src/tests/fixtures/if.js
  packages/devtools-source-map/src/tests/fixtures/if.out.js
  packages/devtools-source-map/src/tests/fixtures/if.out.js.map
  packages/devtools-source-map/src/tests/fixtures/missingmap.js
  packages/devtools-source-map/src/tests/fixtures/noroot.js
  packages/devtools-source-map/src/tests/fixtures/noroot.js.map
  packages/devtools-source-map/src/tests/fixtures/noroot2.js
  packages/devtools-source-map/src/tests/fixtures/noroot2.js.map
  packages/devtools-source-map/src/tests/getContentType.js
  packages/devtools-source-map/src/tests/helpers.js
  packages/devtools-source-map/src/tests/locations.js
  packages/devtools-source-map/src/tests/source-map.js
  packages/devtools-source-map/src/tests/wasm-source-map.js
  packages/devtools-source-map/src/utils/assert.js
  packages/devtools-source-map/src/utils/fetchSourceMap.js
  packages/devtools-source-map/src/utils/index.js
  packages/devtools-source-map/src/utils/sourceMapRequests.js
  packages/devtools-source-map/src/utils/wasmRemap.js
  packages/devtools-source-map/src/worker.js
  packages/devtools-source-map/yarn.lock
  src/components/Editor/CallSites.js
  src/components/Editor/EditorMenu.js
  src/components/Editor/Preview/Popup.js
  src/components/Editor/SearchBar.js
  src/components/QuickOpenModal.js
  src/components/SecondaryPanes/index.js
  src/utils/function.js
  webpack.config.js
  yarn.lock
Labels: pr-wip

#6055 [Breakpoints] Show original breakpoint text
  src/components/Editor/Breakpoint.js
  src/components/SecondaryPanes/Breakpoint.js
  src/components/SecondaryPanes/Breakpoints.js
  src/types.js
Labels: pr-needs-review

#6088 Fix 6065 - Tighten up the breakpoint spacing
  src/components/SecondaryPanes/Breakpoints.css
Labels: pr-needs-review

#6089 Change line based on prettyprint or original source
  src/components/SecondaryPanes/Breakpoint.js
Labels: pr-needs-review

#6039 [Tabs] Refresh the show more dropdown
  package.json
  src/components/shared/Dropdown.css
Labels: pr-wip

#6085 [Sources] updated fix "set directory root" bug
  src/actions/tests/ui.spec.js
  src/components/PrimaryPanes/SourcesTree.js
Labels: pr-needs-review

#6044 [Preview] Remove the root node in the immutable preview and the prototype.
  src/components/Editor/Preview/Popup.js
Labels: pr-needs-review

#6059 [Tabs] Update the show more button 
  assets/images/command-chevron.svg
  src/components/Editor/Tabs.css
  src/components/Editor/Tabs.js
Labels: pr-wip

#6161 [reps] remove some uneeded files
  packages/devtools-reps/README.md
  packages/devtools-reps/bin/copy-assets.js
  packages/devtools-reps/bin/dev-server.js
  packages/devtools-reps/bin/getConfig.js
  packages/devtools-reps/bin/install-yarn
  packages/devtools-reps/bin/publish-assets.js
  packages/devtools-reps/config.js
  packages/devtools-reps/webpack.config.js
  yarn.lock
Labels: devtools-reps

#6160 Last breakpoint style nits
  src/components/SecondaryPanes/Breakpoints.css
  src/components/SecondaryPanes/Expressions.css
  src/components/SecondaryPanes/SecondaryPanes.css
Labels: pr-needs-review

#6182 Fix a few nits from #6166
  src/components/SecondaryPanes/Expressions.js
  src/components/SecondaryPanes/index.js
  src/components/SecondaryPanes/tests/__snapshots__/Expressions.spec.js.snap
  src/components/shared/Accordion.css
Labels: pr-needs-review
