Repository firefox-devtools/debugger, pull requests merged in 2018-12, with the labels that each got.

#7366 Change conditional panel to use location
  src/actions/tests/pending-breakpoints.spec.js
  src/actions/types/UIAction.js
  src/actions/ui.js
  src/components/Editor/ConditionalPanel.js
  src/components/Editor/GutterMenu.js
  src/components/Editor/index.js
  src/components/SecondaryPanes/Breakpoints/Breakpoint.js
  src/components/SecondaryPanes/Breakpoints/BreakpointsContextMenu.js
  src/reducers/breakpoints.js
  src/reducers/ui.js
  src/test/mochitest/browser_dbg-breakpoints-cond.js
  src/utils/breakpoint/index.js
  src/utils/breakpoint/tests/index.spec.js
Labels: pr-needs-review

#7298 7283/fix :formatted showing in tabs/breakpoints sidebar
  src/components/PrimaryPanes/SourcesTreeItem.js
  src/test/mochitest/browser_dbg-sources-querystring.js
  src/utils/quick-open.js
  src/utils/source.js
Labels: pr-wip

#7410 Make gutter marker or breakpoint represent first breakpoint on line
  src/components/Editor/Breakpoints.js
  src/components/SecondaryPanes/Breakpoints/index.js
  src/selectors/index.js
  src/selectors/visibleBreakpoints.js
  src/test/mochitest/browser.ini
  src/test/mochitest/browser_dbg-breakpoints-columns.js
  src/test/mochitest/helpers.js
  src/utils/breakpoint/index.js
  src/utils/breakpoint/tests/index.spec.js
Labels: pr-needs-review

#7455 Provide initial implementation of opening DOM nodes in inspector
  assets/panel/panel.js
  packages/devtools-reps/src/reps/reps.css
  src/actions/toolbox.js
  src/actions/types/index.js
  src/components/Editor/Preview/Popup.js
  src/components/SecondaryPanes/Expressions.js
  src/components/SecondaryPanes/FrameworkComponent.js
  src/components/SecondaryPanes/Scopes.js
  src/components/SecondaryPanes/tests/__snapshots__/Expressions.spec.js.snap
  src/test/mochitest/browser.ini
  src/test/mochitest/browser_dbg-expressions.js
  src/test/mochitest/browser_dbg-inspector-integration.js
  src/test/mochitest/helpers.js
Labels: pr-needs-review

#7342 Function indexes
  src/actions/breakpoints/index.js
  src/actions/breakpoints/syncBreakpoint.js
  src/actions/breakpoints/tests/__snapshots__/breakpoints.spec.js.snap
  src/actions/tests/__snapshots__/ast.spec.js.snap
  src/actions/tests/__snapshots__/pending-breakpoints.spec.js.snap
  src/actions/tests/helpers/breakpoints.js
  src/test/mochitest/browser.ini
  src/test/mochitest/browser_dbg-breakpoints-duplicate-functions.js
  src/test/mochitest/examples/doc-duplicate-functions.html
  src/types.js
  src/utils/breakpoint/astBreakpointLocation.js
  src/utils/breakpoint/index.js
  src/utils/breakpoint/tests/__snapshots__/astBreakpointLocation.spec.js.snap
  src/workers/parser/getSymbols.js
  src/workers/parser/tests/__snapshots__/getSymbols.spec.js.snap
  src/workers/parser/utils/formatSymbols.js
Labels: pr-needs-review

#7487 [Breakpoints] remove immutable.js from xhrBreakpoint reducer
  src/actions/breakpoints/index.js
  src/components/SecondaryPanes/XHRBreakpoints.js
  src/reducers/breakpoints.js
  src/selectors/breakpoints.js
  src/utils/bootstrap.js
Labels: pr-wip

#7496 [Pause points] speed it up
  src/actions/ast/setPausePoints.js
  src/utils/pause/pausePoints.js
Labels: pr-needs-review

#7302 Fix debugger hanging with slow loading source maps
  src/actions/sources/newSources.js
  src/actions/sources/tests/newSources.spec.js
  src/client/firefox/events.js
  src/utils/source-queue.js
  src/utils/test-head.js
Labels: pr-needs-review

#7511 [symbols] stop fetching symbols when loading
  src/actions/ast.js
  src/actions/tests/preview.spec.js
Labels: pr-wip

#7528 Use <span> instead of <img> without SRC
  src/components/Editor/Footer.css
  src/components/Editor/Footer.js
  src/components/Editor/SearchBar.css
  src/components/Editor/Tabs.css
  src/components/Editor/Tabs.js
  src/components/PrimaryPanes/Sources.css
  src/components/PrimaryPanes/SourcesTreeItem.js
  src/components/PrimaryPanes/tests/__snapshots__/SourcesTreeItem.spec.js.snap
  src/components/ProjectSearch.js
  src/components/SecondaryPanes/CommandBar.css
  src/components/SecondaryPanes/CommandBar.js
  src/components/SecondaryPanes/Workers.js
  src/components/shared/AccessibleImage.css
  src/components/shared/AccessibleImage.js
  src/components/shared/Button/CloseButton.js
  src/components/shared/Button/CommandBarButton.js
  src/components/shared/Button/styles/CloseButton.css
  src/components/shared/Button/tests/__snapshots__/CloseButton.spec.js.snap
  src/components/shared/ResultList.css
  src/components/shared/ResultList.js
  src/components/shared/SourceIcon.js
  src/components/shared/Svg.css
  src/components/test/__snapshots__/ProjectSearch.spec.js.snap
Labels: pr-needs-review

#7527 Simplify the Sources Tree icon highlight color
  src/components/PrimaryPanes/Sources.css
  src/components/shared/SourceIcon.css
Labels: pr-needs-review

#7525 Add windowless workers UI
  assets/panel/prefs.js
  bin/copy-modules.js
  src/actions/expressions.js
  src/actions/navigation.js
  src/actions/pause/breakOnNext.js
  src/actions/pause/commands.js
  src/actions/pause/extra.js
  src/actions/pause/fetchScopes.js
  src/actions/pause/index.js
  src/actions/pause/mapFrames.js
  src/actions/pause/mapScopes.js
  src/actions/pause/pauseOnExceptions.js
  src/actions/pause/paused.js
  src/actions/pause/resumed.js
  src/actions/pause/selectFrame.js
  src/actions/pause/setPopupObjectProperties.js
  src/actions/pause/skipPausing.js
  src/actions/pause/tests/pause.spec.js
  src/actions/preview.js
  src/actions/sources/newSources.js
  src/actions/sources/prettyPrint.js
  src/actions/sources/select.js
  src/actions/sources/tests/__snapshots__/prettyPrint.spec.js.snap
  src/actions/sources/tests/select.spec.js
  src/actions/tests/ast.spec.js
  src/actions/tests/expressions.spec.js
  src/actions/tests/preview.spec.js
  src/actions/types/PauseAction.js
  src/actions/types/index.js
  src/client/firefox.js
  src/client/firefox/commands.js
  src/client/firefox/create.js
  src/client/firefox/events.js
  src/client/firefox/types.js
  src/client/firefox/workers.js
  src/components/SecondaryPanes/Workers.css
  src/components/SecondaryPanes/Workers.js
  src/reducers/pause.js
  src/types.js
  src/utils/prefs.js
  src/utils/source-queue.js
  src/utils/sources-tree/addToTree.js
Labels: pr-wip

#7534 re-add support chrome
  src/client/chrome.js
  src/client/chrome/commands.js
  src/client/chrome/create.js
  src/client/chrome/events.js
  src/client/chrome/types.js
  src/client/index.js
Labels: pr-wip

#7512 [symbols] save object property identifiers
  src/workers/parser/getSymbols.js
  src/workers/parser/tests/__snapshots__/getSymbols.spec.js.snap
  src/workers/parser/utils/helpers.js
Labels: pr-needs-review

#7467 Clear the watch expression input box on blur
  src/components/SecondaryPanes/Expressions.js
Labels: pr-wip

#7394 [Parser] Support object destructuring in mapOriginalExpression
  src/workers/parser/mapOriginalExpression.js
  src/workers/parser/tests/mapExpression.spec.js
  src/workers/parser/tests/mapOriginalExpression.spec.js
Labels: pr-needs-review

#7533 Remove extra
  src/actions/ast.js
  src/actions/pause/extra.js
  src/actions/pause/fetchScopes.js
  src/actions/pause/index.js
  src/actions/preview.js
  src/actions/tests/__snapshots__/preview.spec.js.snap
  src/actions/tests/preview.spec.js
  src/actions/types/ASTAction.js
  src/actions/types/PauseAction.js
  src/components/Editor/Preview/Popup.js
  src/components/Editor/Preview/index.js
  src/components/SecondaryPanes/FrameworkComponent.js
  src/components/SecondaryPanes/index.js
  src/reducers/ast.js
  src/reducers/pause.js
  src/test/mochitest/browser_dbg-react-app.js
  src/utils/preview.js
Labels: pr-wip

#7507 Add a + notation in between shortcut labels
  src/components/test/__snapshots__/ShortcutsModal.spec.js.snap
  src/components/test/__snapshots__/WelcomeBox.spec.js.snap
  src/utils/text.js
Labels: pr-needs-review

#7510 Option to not auto expand a node if it has a lot of children
  packages/devtools-components/src/tests/__snapshots__/tree.js.snap
  packages/devtools-components/src/tests/tree.js
  packages/devtools-components/src/tree.js
Labels: pr-needs-review

#7463 Updated the "skip pausing" button to "Deactivate breakpoints".
  assets/panel/debugger.properties
  src/components/SecondaryPanes/CommandBar.js
Labels: discussion

#7482 7190: Save generated file and source map
  assets/panel/debugger.properties
  src/components/Editor/Editor.css
  src/components/Editor/EditorMenu.js
  src/utils/utils.js
Labels: discussion, pr-wip

#7370 [WIP] blackbox original sources
  .travis.yml
  assets/panel/prefs.js
  packages/devtools-source-map/src/index.js
  packages/devtools-source-map/src/source-map.js
  packages/devtools-source-map/src/worker.js
  src/actions/sources/blackbox.js
  src/client/firefox/commands.js
  src/client/firefox/types.js
  src/test/mochitest/browser.ini
  src/test/mochitest/browser_dbg-blackbox-original.js
  src/test/mochitest/helpers.js
  src/utils/prefs.js
Labels: pr-needs-review

#7587 Fixes #7546
  .eslintrc.jsx-a11y
  src/components/shared/Accordion.js
  src/components/shared/tests/__snapshots__/Accordion.spec.js.snap
Labels: pr-needs-review

#7589 Fix cmd/ctrl+shift+b shortcut to toggle conditional breakpoint
  src/components/Editor/index.js
Labels: pr-needs-review

#7597 Change default value for webSocketConnection to remove TCP connection…
  configs/development.json
Labels: pr-needs-review

#7593 Gutter menu fix
  src/components/Editor/GutterMenu.js
  src/test/mochitest/browser_dbg-breakpoints-cond.js
Labels: pr-needs-review

#7561 Don't send whole line across
  src/actions/tests/__snapshots__/project-text-search.spec.js.snap
  src/components/ProjectSearch.css
  src/components/ProjectSearch.js
  src/components/test/__snapshots__/ProjectSearch.spec.js.snap
  src/utils/project-search.js
  src/utils/tests/project-search.spec.js
  src/workers/search/project-search.js
  src/workers/search/tests/__snapshots__/project-search.spec.js.snap
Labels: pr-needs-review

#7603 Shortcuts
  src/components/WelcomeBox.css
Labels: pr-needs-review

#7592 Log points
  assets/panel/debugger.properties
  src/actions/types/UIAction.js
  src/actions/ui.js
  src/components/Editor/ConditionalPanel.js
  src/components/Editor/GutterMenu.js
  src/reducers/ui.js
  src/test/mochitest/browser_dbg-breakpoints-columns.js
  src/test/mochitest/browser_dbg-breakpoints-cond.js
  src/test/mochitest/helpers.js
Labels: pr-needs-review
