Repository firefox-devtools/debugger, pull requests merged in 2018-05, with the labels that each got.

#6053 [Preview] avoid windows getting stuck
  src/actions/preview.js
  src/components/Editor/Preview/Popup.js
  src/components/Editor/Preview/index.js
  src/components/shared/Popover.js
Labels: pr-needs-review

#6159 Revert "Revert "[Exceptions] Update Checkbox Options Language (#6086)…
  assets/panel/debugger.properties
  assets/panel/prefs.js
  src/actions/pause/pauseOnExceptions.js
  src/actions/types/PauseAction.js
  src/client/firefox/commands.js
  src/client/index.js
  src/components/SecondaryPanes/Breakpoints.js
  src/components/SecondaryPanes/CommandBar.js
  src/components/SecondaryPanes/index.js
  src/reducers/pause.js
  src/test/mochitest/browser_dbg-expressions-error.js
  src/test/mochitest/browser_dbg-pause-exceptions.js
  src/test/mochitest/browser_dbg-returnvalues.js
  src/test/mochitest/head.js
  src/utils/prefs.js
Labels: pr-needs-review

#6191 [Preview] an additional tweak
  src/components/Editor/Preview/Popup.js
  src/components/Editor/Preview/index.js
Labels: pr-needs-review

#6194 Adds a few Modal tests
  src/components/shared/Modal.js
  src/components/shared/tests/Modal.spec.js
  src/components/shared/tests/__snapshots__/Modal.spec.js.snap
Labels: pr-needs-review

#6196 Preview to the right
  src/components/shared/BracketArrow.css
  src/components/shared/Popover.css
  src/components/shared/Popover.js
  src/components/shared/tests/__snapshots__/Popover.spec.js.snap
Labels: pr-needs-review

#6187 Works on project-search
  src/workers/search/project-search.js
  src/workers/search/tests/__snapshots__/project-search.spec.js.snap
  src/workers/search/tests/project-search.spec.js
Labels: pr-wip

#6223 [devtools-config] stop using devtools-config in app
  assets/images/Svg.js
  configs/development.json
  package.json
  src/actions/toolbox.js
  src/actions/utils/middleware/history.js
  src/actions/utils/middleware/log.js
  src/components/Editor/index.js
  src/components/test/Outline.spec.js
  src/feature.js
  src/main.js
  src/test/tests-setup.js
  src/utils/assert.js
  src/utils/bootstrap.js
  src/utils/dbg.js
  src/utils/log.js
  src/utils/prefs.js
  src/utils/result-list.js
  src/utils/tests/assert.spec.js
  webpack.config.js
  yarn.lock
Labels: not-actionable

#6227 Makes addTab only dependent on url
  src/actions/sources/select.js
  src/actions/sources/tabs.js
  src/actions/types/SourceAction.js
  src/actions/types/index.js
  src/reducers/sources.js
Labels: pr-wip

#6058 [Tests] add pause on next mochitest
  src/actions/pause/breakOnNext.js
  src/test/mochitest/browser.ini
  src/test/mochitest/browser_dbg-pause-on-next.js
  src/test/mochitest/helpers.js
Labels: pr-wip

#6238 increased expression row height #6166
  src/components/SecondaryPanes/Breakpoints.css
  src/components/SecondaryPanes/Expressions.css
  src/components/SecondaryPanes/SecondaryPanes.css
Labels: discussion

#5971 Use inComponent to detect if the current pause is in a React component
  src/actions/pause/extra.js
  src/actions/sources/loadSourceText.js
  src/actions/tests/__snapshots__/preview.spec.js.snap
  src/actions/tests/fixtures/immutable.js
  src/actions/tests/preview.spec.js
  src/selectors/inComponent.js
  src/selectors/index.js
  src/utils/ast.js
  src/utils/tests/function.spec.js
  src/workers/parser/tests/__snapshots__/getSymbols.spec.js.snap
  src/workers/parser/tests/__snapshots__/pausePoints.spec.js.snap
  src/workers/parser/tests/fixtures/func.js
Labels: pr-needs-review

#6266 [pause] Additional pause point guards
  src/actions/pause/paused.js
  src/reducers/pause.js
  src/utils/pause/stepping.js
Labels: pr-needs-review

#6320 Removes toJS from getGeneratedSource
  src/actions/sources/loadSourceText.js
  src/components/Editor/Footer.js
  src/reducers/sources.js
Labels: pr-needs-review

#6318 Moves ADD_SEARCH_RESULTS to own action creator
  src/actions/project-text-search.js
Labels: pr-needs-review

#6324 Start failing if the build fails
  .travis.yml
  bin/ci/build-firefox.sh
Labels: pr-wip

#6357 Better vertically center the result line in searches
  src/components/shared/SearchInput.css
Labels: pr-needs-review

#6325 [QuickOpen] Loading prompt
  src/components/QuickOpenModal.js
  src/components/shared/SearchInput.css
  src/components/shared/SearchInput.js
Labels: pr-wip

#6298 [src/components] increase test coverage
  src/components/QuickOpenModal.js
  src/components/test/QuickOpenModal.spec.js
  src/components/test/ShortcutsModal.spec.js
  src/components/test/WelcomeBox.spec.js
  src/components/test/__snapshots__/QuickOpenModal.spec.js.snap
  src/components/test/__snapshots__/ShortcutsModal.spec.js.snap
  src/components/test/__snapshots__/WelcomeBox.spec.js.snap
Labels: pr-needs-review

#6366 [Preview] identify if it is react
  src/actions/pause/extra.js
  src/components/Editor/Preview/Popup.js
  src/components/SecondaryPanes/Frames/WhyPaused.js
  src/components/SecondaryPanes/FrameworkComponent.js
  src/types.js
  src/utils/pause/why.js
  src/utils/preview.js
Labels: pr-needs-review

#6341 [reps] Don't include devtools-modules in the reps bundle.
  configs/mozilla-central-mappings.js
  packages/devtools-reps/package.json
  packages/devtools-reps/src/object-inspector/component.js
  packages/devtools-reps/webpack.config.js
  yarn.lock
Labels: pr-wip

#6352 [Tabs] Add Unicode support for various URL & filename & Domain name labels
  src/components/Editor/Tab.js
  src/utils/source.js
  src/utils/sources-tree/getURL.js
  src/utils/tests/source.spec.js
Labels: pr-needs-review

#6265 Add mappedBreakpoints
  src/components/SecondaryPanes/Breakpoint.js
  src/components/SecondaryPanes/Breakpoints.js
  src/selectors/index.js
  src/selectors/mappedBreakpoints.js
  src/utils/breakpoint/index.js
  src/utils/pause/why.js
Labels: pr-wip

#6349 [Tabs] Improve truncation of long filenames
  src/components/Editor/Tab.js
  src/utils/tests/text.spec.js
  src/utils/text.js
Labels: pr-wip

#6326 Cleanup Source Tree
  src/components/PrimaryPanes/SourcesTree.js
  src/components/test/SourcesTree.spec.js
  src/components/test/__snapshots__/SourcesTree.spec.js.snap
  src/utils/sources-tree/addToTree.js
  src/utils/sources-tree/utils.js
Labels: pr-wip

#6263 [Preview] Switch to token-over
  src/actions/preview.js
  src/components/Editor/Preview/Popup.js
  src/components/Editor/Preview/index.js
  src/components/Editor/index.js
  src/components/SecondaryPanes/Breakpoints/Breakpoint.js
  src/components/shared/Popover.js
  src/components/shared/tests/Popover.spec.js
  src/components/shared/tests/__snapshots__/Popover.spec.js.snap
  src/reducers/ast.js
  src/reducers/pause.js
  src/test/mochitest/helpers.js
  src/utils/editor/index.js
  src/utils/editor/token-events.js
Labels: pr-wip

#6424 [Tabs]: Displayed files are not have the same icons
  src/components/PrimaryPanes/SourcesTree.js
  src/components/SecondaryPanes/Breakpoints/index.js
  src/components/test/__snapshots__/SourcesTree.spec.js.snap
Labels: pr-wip
