Repository firefox-devtools/debugger, pull requests merged in 2018-10, with the labels that each got.

#6625 Add types to parser worker methods
  packages/devtools-utils/src/worker-utils.js
  src/actions/ast.js
  src/actions/tests/ast.spec.js
  src/components/SecondaryPanes/Frames/Frame.js
  src/reducers/ast.js
  src/workers/parser/frameworks.js
  src/workers/parser/index.js
  src/workers/parser/mapExpression.js
  src/workers/parser/pausePoints.js
  src/workers/parser/steps.js
  src/workers/parser/types.js
  src/workers/parser/utils/simple-path.js
  src/workers/parser/validate.js
Labels: pr-wip

#6916 [editor] add check in HighlightLine to fix unwanted highlighting
  src/components/Editor/HighlightLine.js
  src/test/mochitest/browser_dbg-editor-highlight.js
Labels: pr-needs-review

#7102 Add tabs for sources without URLs
  src/actions/tabs.js
  src/actions/types/index.js
  src/components/Editor/EditorMenu.js
  src/components/Editor/Tab.js
  src/reducers/sources.js
  src/reducers/tabs.js
  src/selectors/test/getCallStackFrames.spec.js
  src/test/mochitest/browser_dbg-tabs.js
  src/utils/source.js
Labels: pr-needs-review

#7088 [outline] Enable filtering the outline list
  assets/panel/debugger.properties
  src/components/PrimaryPanes/Outline.css
  src/components/PrimaryPanes/Outline.js
  src/components/PrimaryPanes/OutlineFilter.css
  src/components/PrimaryPanes/OutlineFilter.js
  src/components/test/OutlineFilter.spec.js
  src/components/test/__snapshots__/Outline.spec.js.snap
  src/components/test/__snapshots__/OutlineFilter.spec.js.snap
  src/test/mochitest/browser_dbg-outline.js
Labels: pr-needs-review

#7084 6864/keep item focused on tree update
  src/components/PrimaryPanes/SourcesTree.js
  src/test/mochitest/browser_dbg-sources-arrow-keys.js
  src/test/mochitest/browser_dbg-sources.js
  src/test/mochitest/helpers.js
  src/utils/sources-tree/updateTree.js
Labels: pr-needs-review

#6934 UI for XHR Breakpoints
  .travis.yml
  assets/panel/debugger.properties
  assets/panel/prefs.js
  src/actions/breakpoints/index.js
  src/actions/types/BreakpointAction.js
  src/client/firefox/commands.js
  src/client/firefox/types.js
  src/client/index.js
  src/components/SecondaryPanes/XHRBreakpoints.css
  src/components/SecondaryPanes/XHRBreakpoints.js
  src/components/SecondaryPanes/index.js
  src/reducers/breakpoints.js
  src/reducers/types.js
  src/selectors/breakpoints.js
  src/selectors/index.js
  src/test/mochitest/browser.ini
  src/test/mochitest/browser_dbg-chrome-debugging.js
  src/test/mochitest/browser_dbg-xhr-breakpoints.js
  src/test/mochitest/examples/doc-xhr.html
  src/test/mochitest/examples/fetch.js
  src/types.js
  src/utils/bootstrap.js
  src/utils/breakpoint/index.js
  src/utils/prefs.js
Labels: pr-wip

#7124 Added Flow in src/actions/breakpoints/remapLocations.js
  src/actions/breakpoints/remapLocations.js
Labels: pr-wip

#7087 Show querystring in SourcesTree when file has multiple occurrences (#5515)
  src/components/PrimaryPanes/SourcesTreeItem.js
  src/reducers/sources.js
  src/test/mochitest/browser.ini
  src/test/mochitest/browser_dbg-sources-querystring.js
  src/test/mochitest/examples/doc-sources-querystring.html
  yarn.lock
Labels: pr-wip, testing

#7095 Column breakpoints UI
  assets/images/Svg.js
  assets/images/column-marker.svg
  src/components/Editor/CallSite.css
Labels: pr-wip

#7200 Add tooltip to remove expression
  assets/panel/debugger.properties
  src/components/SecondaryPanes/Expressions.js
  src/components/SecondaryPanes/tests/__snapshots__/Expressions.spec.js.snap
Labels: pr-needs-review

#7107 Change tab interface to have blue borders WIP
  src/components/Editor/Tab.js
  src/components/Editor/Tabs.css
  src/components/PrimaryPanes/Sources.css
Labels: pr-wip
