Repository firefox-devtools/debugger, pull requests merged in 2018-08, with the labels that each got.

#6724 Switch to devtools services
  .babel/transform-mc.js
  package.json
  packages/devtools-reps/package.json
  src/client/firefox/commands.js
  src/components/App.js
  src/components/SecondaryPanes/CommandBar.js
  src/utils/prefs.js
  src/utils/text.js
  yarn.lock
Labels: pr-wip

#6678 releases : use native URL class
  .babel/transform-mc.js
  src/test/mochitest/browser_dbg-sources-named-eval.js
  src/test/tests-setup.js
  src/utils/source.js
  src/utils/sources-tree/getURL.js
  src/utils/sources-tree/tests/getUrl.spec.js
  src/utils/sources-tree/treeOrder.js
  src/utils/sources-tree/utils.js
  src/utils/url.js
Labels: pr-needs-review

#6749 [pause] accomodate with blocks
  src/components/SecondaryPanes/Breakpoints/index.js
  src/reducers/pause.js
  src/types.js
  src/utils/pause/mapScopes/index.js
  src/utils/pause/scopes/getScope.js
  src/utils/pause/scopes/getVariables.js
Labels: pr-needs-review

#6742 Add top-level await support
  assets/panel/prefs.js
  flow-typed/npm/@babel/template_vx.x.x.js
  package.json
  src/actions/expressions.js
  src/test/mochitest/browser.ini
  src/test/mochitest/browser_dbg-console-async.js
  src/utils/prefs.js
  src/workers/parser/mapAwaitExpression.js
  src/workers/parser/mapBindings.js
  src/workers/parser/mapExpression.js
  src/workers/parser/mapOriginalExpression.js
  src/workers/parser/tests/mapExpression.spec.js
  src/workers/parser/utils/ast.js
  src/workers/parser/utils/helpers.js
  yarn.lock
Labels: pr-needs-review

#6766 Better format duplicate filename text
  src/utils/source.js
  src/utils/tests/source.spec.js
Labels: pr-wip

#6715 fix the WASM and JS Sources
  src/actions/ast.js
  src/actions/pause/commands.js
  src/actions/sources/newSources.js
  src/actions/sources/prettyPrint.js
  src/client/firefox/create.js
  src/components/PrimaryPanes/SourcesTree.js
  src/components/PrimaryPanes/SourcesTreeItem.js
  src/selectors/getRelativeSources.js
  src/test/mochitest/browser_dbg-sources-named-eval.js
  src/types.js
  src/utils/function.js
  src/utils/isMinified.js
  src/utils/source.js
  src/workers/parser/utils/ast.js
Labels: pr-needs-review

#6743 [breakpoints] Fix syncing cases with toggling
  src/actions/breakpoints/addBreakpoint.js
  src/actions/breakpoints/tests/__snapshots__/breakpoints.spec.js.snap
  src/actions/breakpoints/tests/breakpoints.spec.js
  src/reducers/pending-breakpoints.js
  src/selectors/breakpointSources.js
Labels: pr-wip

#6773 [webreplay] tweak preview and continue to here
  src/actions/preview.js
  src/components/Editor/index.js
Labels: pr-needs-review

#6768 [Tabs] Move actions and reducer for the editor tabs into their own files
  src/actions/index.js
  src/actions/sources/index.js
  src/actions/sources/select.js
  src/actions/tabs.js
  src/reducers/index.js
  src/reducers/sources.js
  src/reducers/tabs.js
  src/reducers/types.js
  src/selectors/index.js
  src/utils/quick-open.js
Labels: pr-wip

#6780 [sources] Cache sources by url
  src/reducers/sources.js
  src/reducers/tabs.js
Labels: pr-needs-review

#6778 [sources] update newSources filter check
  src/actions/sources/newSources.js
Labels: pr-needs-review

#6748 [Editor] fix scrolling while loading
  src/components/Editor/index.js
  src/utils/editor/index.js
Labels: pr-needs-review

#6795 Replace/expand stack frames with original source details
  packages/devtools-source-map/src/index.js
  packages/devtools-source-map/src/utils/getOriginalStackFrames.js
  packages/devtools-source-map/src/worker.js
  src/actions/ast.js
  src/actions/pause/mapFrames.js
  src/actions/pause/tests/pause.spec.js
  src/actions/sources/tests/select.spec.js
  src/actions/tests/ast.spec.js
  src/actions/tests/expressions.spec.js
  src/reducers/pause.js
  src/types.js
Labels: pr-wip

#6811 [preview] jump to definition should respect the current context
  assets/panel/panel.js
  src/actions/pause/paused.js
  src/actions/pause/tests/pause.spec.js
  src/actions/sources/loadSourceText.js
  src/actions/sources/prettyPrint.js
  src/actions/sources/select.js
  src/actions/sources/tests/select.spec.js
  src/components/PrimaryPanes/index.js
  src/components/PrimaryPanes/tests/SourcesTree.spec.js
  src/components/ProjectSearch.js
  src/components/QuickOpenModal.js
  src/components/test/ProjectSearch.spec.js
  src/components/test/QuickOpenModal.spec.js
  src/components/test/__snapshots__/ProjectSearch.spec.js.snap
  src/components/test/__snapshots__/QuickOpenModal.spec.js.snap
  src/test/mochitest/browser_dbg-preview-source-maps.js
  src/test/mochitest/browser_dbg-sourcemaps.js
  src/test/mochitest/browser_dbg-wasm-sourcemaps.js
  src/test/mochitest/helpers.js
  src/test/tests-setup.js
  src/utils/source-maps.js
Labels: pr-needs-review

#6836 Don't repeat filename in subtitle for result list
  src/components/shared/ResultList.js
  src/components/test/__snapshots__/QuickOpenModal.spec.js.snap
Labels: pr-needs-review

#6846 [parser] original language: Accommodate class properties
  .gitignore
  src/test/mochitest/browser.ini
  src/test/mochitest/browser_dbg-sourcemapped-breakpoint-console.js
  src/test/mochitest/examples/doc-sourcemapped.html
  src/test/mochitest/examples/sourcemapped/builds/rollup-babel6/index.js
  src/test/mochitest/examples/sourcemapped/builds/rollup-babel7/index.js
  src/test/mochitest/examples/sourcemapped/builds/rollup-babel7/package.json
  src/test/mochitest/examples/sourcemapped/builds/rollup-babel7/yarn.lock
  src/test/mochitest/examples/sourcemapped/builds/webpack3-babel6/index.js
  src/test/mochitest/examples/sourcemapped/builds/webpack3-babel7/index.js
  src/test/mochitest/examples/sourcemapped/builds/webpack3-babel7/package.json
  src/test/mochitest/examples/sourcemapped/builds/webpack3-babel7/yarn.lock
  src/test/mochitest/examples/sourcemapped/builds/webpack4-babel6/index.js
  src/test/mochitest/examples/sourcemapped/builds/webpack4-babel7/index.js
  src/test/mochitest/examples/sourcemapped/builds/webpack4-babel7/package.json
  src/test/mochitest/examples/sourcemapped/builds/webpack4-babel7/yarn.lock
  src/test/mochitest/examples/sourcemapped/fixtures/babel-classes/input.js
  src/test/mochitest/examples/sourcemapped/output/parcel/babel-classes.js
  src/test/mochitest/examples/sourcemapped/output/parcel/babel-classes.map
  src/test/mochitest/examples/sourcemapped/output/parcel/typescript-classes.js
  src/test/mochitest/examples/sourcemapped/output/parcel/typescript-classes.map
  src/test/mochitest/examples/sourcemapped/output/rollup-babel6/babel-classes.js
  src/test/mochitest/examples/sourcemapped/output/rollup-babel6/babel-classes.js.map
  src/test/mochitest/examples/sourcemapped/output/rollup-babel7/babel-classes.js
  src/test/mochitest/examples/sourcemapped/output/rollup-babel7/babel-classes.js.map
  src/test/mochitest/examples/sourcemapped/output/webpack3-babel6/babel-classes.js
  src/test/mochitest/examples/sourcemapped/output/webpack3-babel6/babel-classes.js.map
  src/test/mochitest/examples/sourcemapped/output/webpack3-babel7/babel-classes.js
  src/test/mochitest/examples/sourcemapped/output/webpack3-babel7/babel-classes.js.map
  src/test/mochitest/examples/sourcemapped/output/webpack3/typescript-classes.js.map
  src/test/mochitest/examples/sourcemapped/output/webpack4-babel6/babel-classes.js
  src/test/mochitest/examples/sourcemapped/output/webpack4-babel6/babel-classes.js.map
  src/test/mochitest/examples/sourcemapped/output/webpack4-babel7/babel-classes.js
  src/test/mochitest/examples/sourcemapped/output/webpack4-babel7/babel-classes.js.map
  src/utils/pause/mapScopes/index.js
Labels: pr-wip

#6800 [breakpoints] memoize Breakpoints component
  src/selectors/visibleBreakpoints.js
Labels: difficulty: medium, discussion, enhancement, pr-wip

#6818 [Tabs/Framework] Cache tabs icon
  src/actions/ast.js
  src/actions/sources/select.js
  src/actions/sources/tests/select.spec.js
  src/actions/tabs.js
  src/actions/tests/tabs.spec.js
  src/actions/types/SourceAction.js
  src/actions/types/index.js
  src/components/shared/SourceIcon.js
  src/reducers/tabs.js
  src/test/mochitest/browser_dbg-tabs.js
  src/test/mochitest/helpers.js
  src/utils/tabs.js
Labels: pr-needs-review

#6809 Remove unecessary check when focusing Tree
  packages/devtools-components/src/tree.css
  packages/devtools-components/src/tree.js
  packages/devtools-reps/src/launchpad/components/Result.js
Labels: pr-needs-review

#6856 [sources] improve updateSource performance
  src/reducers/sources.js
Labels: discussion, enhancement

#6853 [pause] cleanup code
  src/actions/pause/index.js
  src/actions/pause/selectComponent.js
  src/actions/tests/toolbox.spec.js
  src/reducers/pause.js
Labels: pr-wip

#6850 [scopes] detect line-based mappings
  src/utils/pause/mapScopes/index.js
Labels: pr-needs-review

#6861 [dbg] update findSource helper
  assets/dictionary.txt
  docs/dbg.md
  src/utils/dbg.js
Labels: pr-needs-review

#6862 [sources] update tree-node path so it is always unique
  src/components/PrimaryPanes/SourcesTree.js
  src/components/PrimaryPanes/tests/SourcesTree.spec.js
Labels: pr-needs-review

#6869 Preview - speed up the previews
  src/actions/expressions.js
  src/reducers/pause.js
  src/test/mochitest/browser_dbg-preview-source-maps.js
Labels: pr-needs-review

#6867 [tabs] Create tabs for sourcemapped files
  src/actions/ast.js
  src/actions/sources/newSources.js
  src/actions/sources/select.js
  src/actions/sources/tests/newSources.spec.js
  src/actions/sources/tests/select.spec.js
  src/actions/tabs.js
  src/actions/tests/project-text-search.spec.js
  src/actions/tests/tabs.spec.js
  src/actions/types/SourceAction.js
  src/actions/types/index.js
  src/components/Editor/Tab.js
  src/components/PrimaryPanes/SourcesTree.js
  src/components/PrimaryPanes/SourcesTreeItem.js
  src/reducers/sources.js
  src/reducers/tabs.js
  src/test/mochitest/helpers.js
Labels: pr-needs-review
