Repository firefox-devtools/debugger, pull requests merged in 2018-09, with the labels that each got.

#6879 [sources] double check whether a source is present
  src/actions/pause/mapFrames.js
  src/actions/pause/mapScopes.js
  src/actions/sources/loadSourceText.js
  src/actions/sources/newSources.js
  src/client/firefox/commands.js
  src/client/firefox/events.js
  src/reducers/sources.js
  src/test/mochitest/browser.ini
  src/test/mochitest/browser_dbg-reloading.js
Labels: pr-wip

#6943 Removing transition from welcome page links (fixes #6941)
  src/components/WelcomeBox.css
Labels: polish

#6912 [SourceTree] Keyboard arrow behaviour integration tests
  src/test/mochitest/browser.ini
  src/test/mochitest/browser_dbg-sources-arrow-keys.js
  src/test/mochitest/browser_dbg-sources.js
  src/test/mochitest/helpers.js
Labels: pr-wip

#6944 Consistent use of find and files
  assets/panel/debugger.properties
  src/components/Editor/SearchBar.js
  src/components/Editor/tests/__snapshots__/SearchBar.spec.js.snap
  src/components/QuickOpenModal.js
  src/components/ShortcutsModal.js
  src/components/WelcomeBox.js
  src/components/test/__snapshots__/QuickOpenModal.spec.js.snap
  src/components/test/__snapshots__/ShortcutsModal.spec.js.snap
  src/components/test/__snapshots__/WelcomeBox.spec.js.snap
Labels: polish

#6961 [Docs] update contributing.md available issues link
  .github/CONTRIBUTING.md
Labels: pr-wip

#6970 feat: Set accelerator text for context menu items
  assets/panel/debugger.properties
  package.json
  packages/devtools-reps/package.json
  src/components/Editor/EditorMenu.js
  src/components/Editor/GutterMenu.js
  yarn.lock
Labels: pr-needs-review

#6919 Add arrow-key-navigable search history
  src/components/Editor/SearchBar.js
  src/components/Editor/tests/__snapshots__/SearchBar.spec.js.snap
  src/components/ProjectSearch.js
  src/components/shared/SearchInput.js
  src/components/shared/tests/SearchInput.spec.js
  src/components/shared/tests/__snapshots__/SearchInput.spec.js.snap
  src/components/test/__snapshots__/ProjectSearch.spec.js.snap
Labels: pr-wip

#6917 Add "More shortcuts..." in welcome screen
  assets/panel/debugger.properties
  src/components/App.js
  src/components/WelcomeBox.css
  src/components/WelcomeBox.js
  src/components/test/WelcomeBox.spec.js
  src/components/test/__snapshots__/WelcomeBox.spec.js.snap
Labels: discussion, pr-wip

#6992 Use F8 for both pause and breakOnNext commands
  src/components/SecondaryPanes/CommandBar.js
  src/components/SecondaryPanes/tests/CommandBar.spec.js
Labels: pr-wip

#6977 Show some progress when pretty printing
  assets/images/Svg.js
  assets/images/loader.svg
  packages/devtools-reps/src/reps/string.js
  src/actions/sources/prettyPrint.js
  src/components/Editor/Footer.css
  src/components/Editor/Footer.js
  src/components/Editor/index.js
  src/components/Editor/tests/Editor.spec.js
  src/utils/editor/source-documents.js
Labels: pr-wip

#7010 [Search] Put find in file modifers on same line as input and move whole search bar to bottom of editor
  src/components/Editor/Editor.css
  src/components/Editor/SearchBar.css
  src/components/Editor/SearchBar.js
  src/components/Editor/index.js
  src/components/Editor/tests/__snapshots__/SearchBar.spec.js.snap
Labels: pr-needs-review

#7011 Alternative UX changes for issue 6803
  src/components/Editor/Tabs.css
  src/components/PrimaryPanes/Sources.css
  src/components/SecondaryPanes/CommandBar.css
Labels: pr-needs-review

#6975 Async storage tabs
  src/actions/sources/tests/select.spec.js
  src/client/index.js
  src/reducers/tabs.js
  src/test/tests-setup.js
  src/utils/prefs.js
Labels: pr-wip
