Repository firefox-devtools/debugger, pull requests merged in 2019-02, with the labels that each got.

#7862 Fix styling issues with Toggle Panes buttons (fixes #7742)
  images/pane-collapse.svg
  images/pane-expand.svg
  images/toggle-panes.svg
  src/components/App.css
  src/components/Editor/Tabs.js
  src/components/WelcomeBox.js
  src/components/shared/AccessibleImage.css
  src/components/shared/Button/PaneToggleButton.js
  src/components/shared/Button/styles/PaneToggleButton.css
  src/components/shared/Button/tests/PaneToggleButton.spec.js
  src/components/shared/Button/tests/__snapshots__/PaneToggleButton.spec.js.snap
  src/components/shared/Svg.css
  src/components/test/__snapshots__/WelcomeBox.spec.js.snap
Labels: pr-wip

#7836 Fix 7835 - Focus on inputs if plus is clicked but panel is closed
  src/components/SecondaryPanes/Expressions.js
  src/components/SecondaryPanes/XHRBreakpoints.js
  test/mochitest/browser.ini
  test/mochitest/browser_dbg-expressions-focus.js
  test/mochitest/browser_dbg-expressions.js
Labels: pr-needs-review

#7839 Monospace conditional panel and expressions
  src/components/Editor/ConditionalPanel.css
  src/components/SecondaryPanes/Expressions.css
Labels: discussion

#7857 Improving the contrast of the hover background for the buttons in the dark mode - BUG ID - 1513414.
  src/components/App.css
  src/components/shared/Button/styles/CommandBarButton.css
Labels: pr-wip

#7877 Fix 7844: Implement ".devtools-monospace" CSS class
  src/components/PrimaryPanes/Outline.css
  src/components/PrimaryPanes/Outline.js
  src/components/SecondaryPanes/Breakpoints/Breakpoint.js
  src/components/SecondaryPanes/Breakpoints/Breakpoints.css
  src/components/SecondaryPanes/Breakpoints/tests/__snapshots__/Breakpoint.spec.js.snap
  src/components/test/__snapshots__/Outline.spec.js.snap
Labels: pr-wip

#7865 Fix 7830 mapBindings throws
  src/workers/parser/mapBindings.js
  src/workers/parser/tests/mapBindings.spec.js
Labels: pr-needs-review

#7760 Show command bar if paused and secondary panel hidden
  src/actions/pause/paused.js
  src/actions/pause/resumed.js
  src/actions/types/PauseAction.js
  src/components/Editor/Tabs.css
  src/components/Editor/Tabs.js
  src/reducers/pause.js
Labels: needs-ux, pr-wip

#7818 spread the options object inside the pendingBreakpoint
  src/actions/breakpoints/addBreakpoint.js
  src/actions/breakpoints/tests/syncing.spec.js
  src/actions/tests/__snapshots__/pending-breakpoints.spec.js.snap
  src/actions/tests/helpers/breakpoints.js
  src/components/SecondaryPanes/Breakpoints/tests/BreakpointsContextMenu.spec.js
  src/reducers/tests/breakpoints.spec.js
  src/utils/breakpoint/index.js
Labels: pr-needs-review

#7837 Add context menus for handling breakpoints on a line
  assets/panel/debugger.properties
  src/actions/breakpoints/index.js
  src/components/Editor/menus/breakpoints.js
Labels: pr-wip

#7910 [Fix for #7851] After #7796 relativeSources attributes were not updated
  src/actions/sources/tests/blackbox.spec.js
  src/reducers/sources.js
Labels: pr-wip

#7908 Fix 6734 - Prevent two active breakpoints
  src/components/SecondaryPanes/Breakpoints/Breakpoint.js
Labels: pr-needs-review

#7770 Run mozilla-central Frames dependent tests on Travis.
  .travis.yml
Labels: pr-wip

#7911 Add syntax highlighting to conditional panel
  src/components/Editor/ConditionalPanel.css
  src/components/Editor/ConditionalPanel.js
  src/utils/editor/source-editor.js
  test/mochitest/helpers.js
Labels: pr-wip

#7926 Fix getting-setup.md
  docs/getting-setup.md
Labels: pr-needs-review

#7811 Fix logpoints bug
  assets/panel/debugger.properties
  src/components/Editor/Breakpoint.js
  src/components/Editor/ColumnBreakpoint.js
  src/components/Editor/ColumnBreakpoints.css
  src/components/Editor/ConditionalPanel.js
  src/components/Editor/Editor.css
  src/components/Editor/menus/breakpoints.js
  src/components/SecondaryPanes/Breakpoints/Breakpoint.js
  src/components/SecondaryPanes/Breakpoints/Breakpoints.css
  src/components/SecondaryPanes/Breakpoints/BreakpointsContextMenu.js
  src/types.js
  test/mochitest/browser_dbg-breakpoints-cond.js
  test/mochitest/helpers.js
Labels: pr-needs-review

#7721 XHR breakpoints with methods
  src/components/SecondaryPanes/XHRBreakpoints.css
  src/components/SecondaryPanes/XHRBreakpoints.js
  src/components/SecondaryPanes/tests/XHRBreakpoints.spec.js
  src/components/SecondaryPanes/tests/__snapshots__/XHRBreakpoints.spec.js.snap
  test/mochitest/browser_dbg-xhr-breakpoints.js
  test/mochitest/examples/fetch.js
Labels: pr-needs-review

#7812 Add black box option to context menu for source tree items and source header
  src/components/Editor/Tab.js
  src/components/PrimaryPanes/SourcesTreeItem.js
  src/components/PrimaryPanes/tests/SourcesTreeItem.spec.js
  src/components/PrimaryPanes/tests/__snapshots__/SourcesTreeItem.spec.js.snap
  src/utils/tabs.js
Labels: pr-needs-review

#7924 Improves on debugging the debugger doc to make easier the "inception".
  docs/debugging-the-debugger.md
Labels: pr-needs-review

#7875 Add better keyboard support for focusable elements inside ObjectInspe…
  packages/devtools-components/src/tests/__snapshots__/tree.js.snap
  packages/devtools-components/src/tests/tree.js
  packages/devtools-components/src/tree.js
  packages/devtools-reps/src/object-inspector/components/ObjectInspector.js
  packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/classnames.js.snap
  packages/devtools-reps/src/object-inspector/tests/component/__snapshots__/window.js.snap
  packages/devtools-reps/src/object-inspector/types.js
  src/components/SecondaryPanes/Expressions.js
  src/components/SecondaryPanes/Scopes.js
  src/components/SecondaryPanes/tests/__snapshots__/Expressions.spec.js.snap
  src/components/shared/tests/__snapshots__/ManagedTree.spec.js.snap
  src/components/test/__snapshots__/ProjectSearch.spec.js.snap
Labels: pr-wip

#7959 Fix Bugzilla 1108132 - Provide code wrapping pref for debugger
  assets/panel/prefs.js
  src/utils/editor/create-editor.js
  src/utils/prefs.js
Labels: discussion, pr-needs-review

#7949 Fix 7947 - Show context menu when right-clicking directory
  src/components/PrimaryPanes/SourcesTreeItem.js
  src/components/PrimaryPanes/tests/SourcesTreeItem.spec.js
Labels: pr-needs-review

#7937 Improve EventListener UI
  src/components/SecondaryPanes/EventListeners.css
  src/components/SecondaryPanes/EventListeners.js
Labels: pr-wip

#7948 Remove postcss-bidirection
  docs/local-development.md
  postcss.config.js
  src/components/ProjectSearch.css
  src/components/SecondaryPanes/Breakpoints/Breakpoints.css
  src/components/SecondaryPanes/CommandBar.css
  src/components/SecondaryPanes/Expressions.css
  src/components/SecondaryPanes/XHRBreakpoints.css
  src/components/WelcomeBox.css
  src/components/shared/Dropdown.css
  src/components/shared/SearchInput.css
Labels: pr-needs-review

#7950 Modified the Angular regex
  src/utils/pause/frames/getLibraryFromUrl.js
  src/utils/pause/frames/tests/annotateFrames.spec.js
  src/utils/pause/frames/tests/getLibraryFromUrl.spec.js
Labels: :books: pr-needs-review

#7996 Only wait for the main thread to set/clear breakpoints.
  src/client/firefox/commands.js
Labels: :books: pr-needs-review

#7988 Update mochitests docs
  assets/dictionary.txt
  docs/mochitests.md
Labels: :books: pr-needs-review

#7893 fixed keyboard shortcuts on MacOS [#7892]
  src/components/WelcomeBox.css
  src/utils/text.js
Labels: :books: pr-needs-review

#7957 Ensure consistent filenames throughout tabs, tree, and search
  src/components/PrimaryPanes/SourcesTreeItem.js
  src/components/PrimaryPanes/tests/SourcesTreeItem.spec.js
  src/components/PrimaryPanes/tests/__snapshots__/SourcesTreeItem.spec.js.snap
  src/utils/sources-tree/getURL.js
  src/utils/sources-tree/tests/getUrl.spec.js
Labels: :books: pr-needs-review

#7979 Update debugging-the-debugger.md
  assets/dictionary.txt
  docs/debugging-the-debugger.md
Labels: :books: pr-needs-review

#7992 Fixing source selection with the keyboard (fixes #7874) (#7874)
  src/components/PrimaryPanes/SourcesTree.js
  src/components/PrimaryPanes/tests/SourcesTree.spec.js
  src/components/PrimaryPanes/tests/__snapshots__/SourcesTree.spec.js.snap
Labels: :books: pr-needs-review

#7999 Fix community-team.md
  docs/community-team.md
Labels: :books: pr-needs-review

#8000 [Breakpoints] Improve column breakpoint performance
  packages/devtools-source-map/src/index.js
Labels: :books: pr-needs-review

#7984 [Sources] follow up tweaks for the source consolidation
  assets/panel/prefs.js
  src/actions/sources/newSources.js
  src/actions/sources/prettyPrint.js
  src/components/PrimaryPanes/tests/__snapshots__/SourcesTree.spec.js.snap
  src/components/PrimaryPanes/tests/__snapshots__/SourcesTreeItem.spec.js.snap
  src/components/SecondaryPanes/Frames/tests/__snapshots__/Frame.spec.js.snap
  src/components/SecondaryPanes/Frames/tests/__snapshots__/Frames.spec.js.snap
  src/components/SecondaryPanes/Frames/tests/__snapshots__/Group.spec.js.snap
  src/reducers/sources.js
  src/types.js
  src/utils/prefs.js
  src/utils/sources-tree/tests/__snapshots__/updateTree.spec.js.snap
  src/utils/test-mockup.js
  src/workers/parser/tests/sources.spec.js
Labels: :books: pr-needs-review

#8006 [Breakpoints] getBreakpointPositionsForLine should return null when n…
  src/reducers/breakpoints.js
Labels: :books: pr-needs-review

#7975 Add a BigInt rep.
  packages/devtools-reps/src/object-inspector/tests/utils/should-render-roots-in-reps.js
  packages/devtools-reps/src/object-inspector/utils/node.js
  packages/devtools-reps/src/reps/big-int.js
  packages/devtools-reps/src/reps/rep.js
  packages/devtools-reps/src/reps/stubs/big-int.js
  packages/devtools-reps/src/reps/tests/big-int.js
Labels: :books: pr-needs-review

#8001 [Breakpoints] memoize breakpoint position fetching
  src/actions/breakpoints/addBreakpoint.js
  src/actions/breakpoints/breakpointPositions.js
  src/actions/breakpoints/index.js
  src/actions/breakpoints/syncBreakpoint.js
  src/actions/breakpoints/tests/breakpointPositions.spec.js
  src/actions/types/BreakpointAction.js
  src/reducers/breakpoints.js
  src/utils/defer.js
Labels: :books: pr-needs-review

#7982 Remove immutables
  src/actions/ast/setInScopeLines.js
  src/actions/types/ASTAction.js
  src/reducers/ast.js
  src/reducers/types.js
Labels: :books: pr-needs-review

#8038 Added Firefox Nightly CLI launch instructions
  README.md
  docs/getting-setup.md
Labels: :books: pr-needs-review

#7994 Prevent debug line zombie
  src/components/Editor/DebugLine.js
  test/mochitest/browser.ini
  test/mochitest/browser_dbg-debug-line.js
  test/mochitest/helpers.js
Labels: :books: pr-needs-review

#8044 Fix 8026 - Prevent breakpoint label from triggering checkbox focus
  src/components/SecondaryPanes/Breakpoints/Breakpoint.js
  src/components/SecondaryPanes/Breakpoints/tests/Breakpoint.spec.js
  src/components/SecondaryPanes/Breakpoints/tests/__snapshots__/Breakpoint.spec.js.snap
Labels: :books: pr-needs-review
