Repository firefox-devtools/debugger, pull requests merged in 2019-03, with the labels that each got.

#8010 Fixes Regex for React Libraries
  src/utils/pause/frames/getLibraryFromUrl.js
  src/utils/pause/frames/tests/getLibraryFromUrl.spec.js
Labels: :books: pr-needs-tests

#8053 Ensuring long strings get re-rendered when their loaded properties ar…
  packages/devtools-components/src/tests/__snapshots__/tree.js.snap
  packages/devtools-components/src/tests/tree.js
  packages/devtools-components/src/tree.js
  packages/devtools-reps/src/object-inspector/components/ObjectInspector.js
  packages/devtools-reps/src/object-inspector/tests/component/should-item-update.js
Labels: :books: pr-needs-review

#8037 Fix 7799 - Restore pretty print shim to tab context menu
  src/components/Editor/Tab.js
Labels: :books: pr-needs-review

#8050 Unify array creation style in SecondaryPanes getStartItems and getEndItems
  src/components/SecondaryPanes/index.js
Labels: :books: pr-needs-review

#8029 Add focus-within for showing breakpoint's delete button
  src/components/SecondaryPanes/Breakpoints/Breakpoints.css
Labels: :books: pr-wip

#8052 Fix #7840 - Remove blackboxed text to prevent overflow
  assets/panel/debugger.properties
  src/components/Editor/Footer.css
  src/components/Editor/Footer.js
Labels: :books: pr-needs-review

#8069 Fix #8033 - Open node from the object inspector in popups
  src/components/Editor/Preview/Popup.js
  test/mochitest/browser_dbg-inspector-integration.js
  test/mochitest/helpers.js
Labels: :books: pr-needs-review

#8063 Update pull-requests.md
  docs/pull-requests.md
Labels: :books: pr-wip

#8086 Fix #8084 - Vue.js icon missing in Frames
  src/components/SecondaryPanes/Frames/Frames.css
  src/components/shared/AccessibleImage.css
  src/components/shared/SourceIcon.css
Labels: :books: pr-needs-review

#8072 Fix #7956 - Show falsy values in preview
  src/actions/preview.js
  test/mochitest/browser_dbg-preview.js
Labels: :books: pr-needs-review

#8079 fix: make search input more responsive
  src/components/shared/SearchInput.css
Labels: :books: pr-wip

#8024 Improve SourcesTreeItem.mapStateToProps performance by storing plain urls
  src/actions/sources/tests/__snapshots__/newSources.spec.js.snap
  src/actions/sources/tests/newSources.spec.js
  src/actions/sources/tests/querystrings.spec.js
  src/reducers/sources.js
  src/utils/source.js
Labels: :books: pr-needs-tests, :books: pr-wip

#7978 added no sources message in Sources Pane
  src/components/PrimaryPanes/SourcesTree.js
  src/components/PrimaryPanes/tests/SourcesTree.spec.js
  src/components/PrimaryPanes/tests/__snapshots__/SourcesTree.spec.js.snap
Labels: :books: pr-needs-tests

#8039 Always render footer
  src/components/App.js
  src/components/Editor/Editor.css
  src/components/Editor/Footer.css
  src/components/Editor/Footer.js
  src/components/Editor/index.js
  src/components/Editor/tests/__snapshots__/Editor.spec.js.snap
  src/components/Editor/tests/__snapshots__/Footer.spec.js.snap
  src/components/WelcomeBox.css
  src/components/WelcomeBox.js
  src/components/test/__snapshots__/WelcomeBox.spec.js.snap
  src/utils/editor/index.js
  src/utils/editor/tests/editor.spec.js
Labels: :books: pr-wip

#8094 Aligned breakpoints and XHR breakpoints panes
  src/components/SecondaryPanes/Breakpoints/Breakpoints.css
  src/components/SecondaryPanes/Breakpoints/index.js
  src/components/SecondaryPanes/Expressions.css
  src/components/SecondaryPanes/SecondaryPanes.css
  src/components/SecondaryPanes/XHRBreakpoints.css
  src/components/shared/Accordion.css
  test/mochitest/browser_dbg-breakpoints-actions.js
  test/mochitest/browser_dbg-breakpoints-cond.js
  test/mochitest/browser_dbg-breakpoints.js
Labels: :books: pr-needs-review

#8114 Switch watch expression's delete button
  src/components/SecondaryPanes/Expressions.css
Labels: :books: pr-needs-review

#8136 8118/fix quick open modal nan bug
  src/components/QuickOpenModal.js
  src/components/test/QuickOpenModal.spec.js
Labels: :books: pr-needs-review

#8137 [QuickOpen] show the end of the path
  src/components/shared/ResultList.css
  src/utils/quick-open.js
Labels: :books: pr-needs-review

#8066 Align watch expressions and scopes pane
  packages/devtools-components/src/tree.css
  packages/devtools-reps/src/object-inspector/components/ObjectInspector.css
  src/components/PrimaryPanes/Sources.css
  src/components/SecondaryPanes/Expressions.css
  src/components/SecondaryPanes/Scopes.css
Labels: :books: pr-needs-review

#8170 Render href attribute in String rep URLs.
  packages/devtools-reps/src/reps/string.js
  packages/devtools-reps/src/reps/tests/string-with-url.js
Labels: :books: pr-needs-review

#8173 Fix string linkification greediness.
  packages/devtools-reps/src/reps/rep-utils.js
  packages/devtools-reps/src/reps/string.js
  packages/devtools-reps/src/reps/tests/string-with-url.js
Labels: :books: pr-needs-review
