Repository firefox-devtools/debugger, pull requests merged in 2019-04, with the labels that each got.

#8157 Fixed Horizontal scrolling in the debugger secondary panel
  src/components/SecondaryPanes/Breakpoints/Breakpoints.css
  src/components/SecondaryPanes/Expressions.css
  src/components/SecondaryPanes/Scopes.css
  src/components/SecondaryPanes/SecondaryPanes.css
  src/components/SecondaryPanes/XHRBreakpoints.css
Labels: :books: pr-wip

#8134 Keep QuickOpenModal resultCount in bounds
  src/components/QuickOpenModal.js
  src/components/test/QuickOpenModal.spec.js
Labels: :books: pr-needs-review

#8175 [SourcesTree] Sort SourcesTree by url when files share same name
  src/utils/sources-tree/addToTree.js
  src/utils/sources-tree/treeOrder.js
  test/mochitest/browser_dbg-sources-querystring.js
Labels: :books: pr-needs-review

#8158 8064-footer
  src/components/Editor/Footer.css
  src/components/Editor/Footer.js
  src/components/Editor/tests/__snapshots__/Footer.spec.js.snap
Labels: :books: pr-wip

#8179 remove skip from grip.js test
  packages/devtools-reps/src/reps/tests/grip.js
Labels: :books: pr-wip

#8077 Apply SourceMaps type to redux actions
  flow-typed/debugger-html.js
  packages/devtools-source-map/src/index.js
  packages/devtools-source-map/src/utils/getOriginalStackFrames.js
  packages/devtools-source-map/src/utils/wasmXScopes.js
  src/actions/breakpoints/breakpointPositions.js
  src/actions/breakpoints/remapLocations.js
  src/actions/pause/mapFrames.js
  src/actions/sources/newSources.js
  src/actions/sources/prettyPrint.js
  src/actions/types/index.js
  src/types.js
  src/utils/bootstrap.js
  src/utils/pause/mapScopes/getApplicableBindingsForOriginalPosition.js
  src/utils/pause/mapScopes/index.js
  src/utils/pause/mapScopes/rangeMetadata.js
  src/utils/source-maps.js
Labels: :books: pr-wip

#8163 Issue #8049 Make WhyPaused more visible
  images/info.svg
  src/components/App.js
  src/components/SecondaryPanes/Frames/WhyPaused.css
  src/components/SecondaryPanes/Frames/WhyPaused.js
  src/components/SecondaryPanes/Frames/index.js
  src/components/SecondaryPanes/WhyPaused.css
  src/components/SecondaryPanes/WhyPaused.js
  src/components/SecondaryPanes/index.js
  src/components/shared/AccessibleImage.css
  src/components/test/WhyPaused.spec.js
  src/components/test/__snapshots__/WhyPaused.spec.js.snap
Labels: :books: pr-needs-review, discussion, needs-ux

#8201 Improve performance of "Go to file"
  src/components/QuickOpenModal.js
  src/components/test/QuickOpenModal.spec.js
  src/components/test/__snapshots__/QuickOpenModal.spec.js.snap
  src/utils/quick-open.js
  src/utils/result-list.js
  test/mochitest/browser_dbg-quick-open.js
Labels: :books: pr-wip
